### ISSUE TITLE
Cannot deploy to Zeit

### ISSUE THREAD

**Issue by adventurini** [hmmChase/next-graphql-starter#261]
The main demo link isn't working either, so I am sure it is a build issue. Here is the error:

```Cannot find module: next/dist/next-server/server/render```

I have tried to roll back / ahead versions of Next. The file does exist and looks like it is fine. 

There are 17 runtime errors on Zeit Now when deployed. 7 are associated with the favicon, 2 are associated with Head, and the other 6 are random.

**Comment by hmmChase** [comment]
Everything should be working now
